version: "3.9"

services:
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - default

  taxabooking:
    image: braunerr/taxabooking:latest
    container_name: taxabooking
    environment:
      - FilePath=/srv/files/
      - HostnameRabbit=rabbitmq-dev
    ports:
      - "8080:80"
    networks:
      - default
    volumes:
      - files:/srv/files
    depends_on:
      - rabbitmq

  maintenance:
    image: braunerr/maintenance:latest
    container_name: maintenance
    environment:
      - FilePath=/srv/files/
      - HostnameRabbit=rabbitmq-dev
    ports:
      - "8081:80"
    networks:
      - default
    volumes:
      - files:/srv/files
    depends_on:
      - rabbitmq

  planning:
    image: braunerr/planningservice:latest
    container_name: planning
    environment:
      - FilePath=/srv/files/
      - HostnameRabbit=rabbitmq-dev
    ports:
      - "8000:80"
    networks:
      - default
    volumes:
      - files:/srv/files
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:management
    hostname: "rabbitmq-dev"
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  files:
    external: false

networks:
  default:
    driver: bridge
  loki:
